// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AchievementsBoardFive: typeof import('./src/components/achievementsBoardFive.vue')['default']
    AchievementsBoardFour: typeof import('./src/components/achievementsBoardFour.vue')['default']
    AchievementsBoardOne: typeof import('./src/components/achievementsBoardOne.vue')['default']
    AchievementsBoardThree: typeof import('./src/components/achievementsBoardThree.vue')['default']
    AchievementsBoardTwo: typeof import('./src/components/achievementsBoardTwo.vue')['default']
    AdvertisementBoard: typeof import('./src/components/advertisementBoard.vue')['default']
    ArticleBoard: typeof import('./src/components/articleBoard.vue')['default']
    BirthdayBoard: typeof import('./src/components/birthdayBoard.vue')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    DefaultBoard: typeof import('./src/components/defaultBoard.vue')['default']
    EmployeeBoard: typeof import('./src/components/employeeBoard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    OneBoard: typeof import('./src/components/OneBoard.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RussiaDayBoard: typeof import('./src/components/russiaDayBoard.vue')['default']
  }
}

export { }
