version: '3'
services:

    postgres:
        image: postgres:10.6-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: wallboard
        ports:
            - 15432:5432
        volumes:
            - postgres-data:/var/lib/posgresql/data

    frontend:
        image: registry.digitalskynet.com/devops/wallboard/dev/frontend
        restart: unless-stopped
        build:
            context: .
            dockerfile: frontend.Dockerfile
        environment:
            W_BACKEND_URL: backend
            W_DNS_RESOLVER: 127.0.0.11
            W_PUBLIC_URL: http://localhost:3333
        ports:
            - 3333:80

    backend:
        image: registry.digitalskynet.com/devops/wallboard/dev/backend
        restart: unless-stopped
        build:
            context: .
            dockerfile: backend.Dockerfile
        ports:
            - 5000:80
        environment:
            W_ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=wallboard;Username=postgres;Password=postgres;

volumes:
    postgres-data:
