stages:
  - build
  - deploy

variables:
  BRANCH_ENV_MAPPING: development=dev;main=dev
  APP_NAME: visualizer

include:
  - project: 'digitalskynet/gitlab-essentials'
    ref: master
    file: '/ci/build/docker.yml'
  - project: 'digitalskynet/gitlab-essentials'
    ref: master
    file: '/ci/deploy/kapitan.yml'

just build proxy:
  extends: .just_build_container_template
  variables:
    APP_TIER: proxy

build proxy:
  extends: .build_container_template
  variables:
    APP_TIER: proxy
